strings = {
    "INTERNAL_SERVER_ERROR": "That didn't work! Please try again",
    "PROBLEM_REPORTED": "Sorry, we didn't expect that request. This problem has been reported to our team and we are working on resolving this.",
    "DONE": "Done!",
    "REQUIRES_LOGIN": "Please login.",
    "POST_CREATED": "The post was successfully created.",
    "USER_CREATED": "User was successfully created.",
    "USER_ALREADY_REGISTERED": "User is already registered.",
    "USERNAME_NOT_AVAILABLE": "Username is already in use.",
    "USERNAME_NOT_FOUND": "Entered username is wrong.",
    "USER_NOT_FOUND": "User not found.",
    "STARTED_FOLLOWING": "You are now a follower.",
    "ALREADY_FOLLOWING": "User is already a follower.",
    "USERNAME_PASSWORD_CREATED": "Username and password are saved successfully.",
    "PAGE_NOT_FOUND": "Requested page does not exist.",
    "FEEDS_NOT_FOUND": "Feeds are not available now.",
    "FEEDS_FOUND": "Feeds are available.",
    "NOT_FOLLOWING_ANYONE": "You are not following anyone",
    "SUGGESTIONS_NOT_FOUND": "Suggestions not available.",
    "SUGGESTIONS_FOUND": "Suggestions are available.",
    "LOGIN_USERNAME_MISSING": "Username is missing.",
    "LOGIN_PASSWORD_MISSING": "Password is missing.",
    "WRONG_LOGIN_PASSWORD": "Entered password is wrong.",
    "INVALID_CREDENTIALS": "Username or password is wrong",
    "LOGIN_OK": "Login successfull!",
    "ACCESS_TOKEN_EXPIRED": "Access token has been expired.",
    "ACCOUNT_DEACTIVATED": "Your account has been deactivated.",
    "LOGOUT_OK": "Logout successfull!",
    "PAGINATION_OUT_OF_BOUNDS": "Could not load the page.",
    "RESPONSE_VALIDATION_FAILED": "We could not generate response for the request. We are working on fixing this.",
    "FORBIDDEN": "You don't have sufficient permissions.",
    "UNPROCESSABLE_ENTITY": "Given input is not sufficient."
}
