strings = {
    "INTERNAL_SERVER_ERROR": "That didn't work! Please try again",
    "PROBLEM_REPORTED": "Sorry, we didn't expect that request. This problem has been reported to our team and we are working on resolving this.",
    "DONE": "Done!",
    "DECK_TITLE_MISSING": "Please provide a title for the deck",
    "DECK_DESC_MISSING": "Please provide a description for the deck",
    "DECK_INSUFFICIENT_TAGS": "Need at least 3 tags for the deck",
    "DECK_TOO_MANY_TAGS": "Cannot add more than 10 tags to a deck",
    "REQUIRES_LOGIN": "Please login.",
    "DECK_CREATED": "The deck was successfully created.",
    "DECK_DELETED": "The deck was successfully deleted.",
    "QUESTION_TITLE_MISSING": "Please provide a title for the question.",
    "QUESTION_DEF_MISSING": "Please provide a definition for the question",
    "PAGE_NOT_FOUND": "Requested page does not exist.",
    "QUESTION_IMG_SRC_MISSING": "Source field of image is missing.",
    "QUESTION_IMG_SRC_INVALID": "Source field of image is invalid.",
    "QUESTIONS_ADDED": "Questions added to deck.",
    "DECK_QUESTIONS_EMPTY": "No questions to add.",
    "DECK_NOT_FOUND": "Could not locate the deck.",
    "DECK_UPDATED": "The deck was successfully updated.",
    "NOT_DECK_OWNER": "You need to be owner of this deck to add questions.",
    "LOGIN_USERNAME_MISSING": "Username is missing.",
    "LOGIN_PASSWORD_MISSING": "Password is missing.",
    "LOGIN_CLIENT_ID_MISSING": "Client ID is missing.",
    "LOGIN_GRANT_TYPE_INVALID": "Grant type is invalid.",
    "INVALID_CREDENTIALS": "Username or password is wrong",
    "LOGIN_OK": "Login successfull!",
    "ACCOUNT_DEACTIVATED": "Your account has been deactivated.",
    "LOGOUT_OK": "Logout successfull!",
    "PAGINATION_OUT_OF_BOUNDS": "Could not load the page.",
    "IMAGE_DATA_MISSING": "Image data is missing.",
    "RESPONSE_VALIDATION_FAILED": "We could not generate response for the request. We are working on fixing this.",
    "IMAGE_FETCH_ERROR": "Error in fetching image from specified url.",
    "FILE_NOT_ADDED": "File could not be uploaded.",
    "FILE_ADDED": "File uploaded successfully.",
    "FORBIDDEN": "You don't have sufficient permissions.",
    "MAGIC_IDENTITY_MISSING": "Magic identity is missing",
    "INVALID_MAGIC_TOKEN": "Magic token not found",
    "MAGIC_LINK_CREATED": "Magic link created successfully",
    "STUDY_CARD_CREATED": "The study card was successfully created.",
    "STUDY_CARD_DELETED": "The study card was successfully deleted.",
    "CANNOT_UPDATE_STUDY_CARD": "The study card template cannot be updated.",
    "CANNOT_DELETE_STUDY_CARD": "The study card template cannot be deleted.",
    "STUDY_CARD_NOT_FOUND": "Could not locate the study card.",
    "CARD_TEMPLATE_CREATED": "The card template was successfully created.",
    "CARD_TEMPLATE_DELETED": "The card template was successfully deleted.",
    "CANNOT_UPDATE_CARD_TEMPLATE": "The card template was successfully deleted.",
    "CARD_TEMPLATE_NOT_FOUND": "The card template not found.",
    "TEMPLATE_NOT_VALID": "Card template not valid.",
    "CARD_TYPE_NOT_VALID": "Card type is not valid",
    "PERMISSION_NOT_FOUND": "Permission could not be found.",
    "INVALID_AUTH_STATE": "Unauthorized! auth state not found",
    "ROLE_NOT_FOUND": "Role not found.",
    "ROLE_HAS_ATTACHMENTS": "The role is assigned to users.",
    "IDENTITY_MISSING": "Need at least one of mobile or email.",
    "EMAIL_TAKEN": "Email address is already in use",
    "MOBILE_TAKEN": "Mobile number is already in use",
    "ROLE_ASSIGNMENT_ERROR": "Cannot assign given roles to this user.",
    "USER_REGISTERED": "User was successfully registered.",
    "USER_NOT_FOUND": "User does not exist.",
    "USER_UPDATED": "User details were updated.",
    "CANNOT_DELETE_SELF_ACCOUNT": "Cannot delete your own account.",
    "ROLE_CREATED": "Role created successfully.",
    "CANNOT_SPLIT_A_BASIC_CARD": "Cannot split a card of type basic",
    "PERMISSION_CREATED": "Permission was created.",
    "INVALID_SEARCH": "Search is invalid",
    "MULTI_DECK_RECALL_NOT_SUPPORTED": "Study on collections is not available for you.",
    "DUPLICATE_RECALLS": "Duplicate cards in study submission.",
    "CARD_NOT_FOUND": "Card was not found in the deck.",
    "INVALID_USERNAME": "Username not found.",
    "INVALID_OTP": "OTP is not correct.",
    "CARD_DIAGRAM_NOT_VALID": "Card diagram is not valid",
    "DECK_UNLOCKED": "Deck is Unlocked",
    "ALREADY_PURCHASED": "Deck is already Unlocked",
    "DECK_LIKED": "Deck liked",
    "DECK_UNLIKED": "Deck unliked",
    "TRENDING_SET_NOT_FOUND": "Trending set not found",
    "QUERY_STRING_TOO_SMALL": "Query string is too small",
    "RATE_LIMITED": "Hold on there Power User! You have exceeded your request quota. Please try again after some time.",
    "USER_NAME_UPDATED": "User name updated.",
    "USER_NAME_NOT_UPDATED": "User name not updated.",
    "USER_PROFILE_IMAGE_ADDED": "User profile image added.",
    "USER_PROFILE_IMAGE_NOT_ADDED": "User profile image cannot be added.",
    "USER_PROFILE_NOT_CREATED": "User profile cannot be created.",
    "QUESTION_UPDATED": "Question saved successfully.",
    "QUESTION_DELETED": "Question was deleted.",
    "NOT_CARD_OWNER": "You are not allowed to edit this card!",
    "TRENDING_SET_UPDATED": "Trending set has been updated successfully.",
    "TRENDING_SET_CREATED": "Trending set has been created successfully.",
    "QUESTION_NOT_FOUND": "Question not found!",
    "QUESTION_NOT_ADDED": "Question not added.",
    "QUESTION_NOT_DELETED": "Question not deleted.",
    "USER_DETAILS_UPDATED": "User details updated.",
    "STUDY_PLAN_EXISTS": "Deck is already added to study plan.",
    "REVIEW_TARGET_TOO_LARGE": "Number of daily cards is too large.",
    "INVALID_DATE": "The date provided is invalid",
    "PLAN_TOO_AGGRESSIVE": "Study plan is too aggressive",
    "STUDY_PLAN_CREATED": "Study plan created",
    "STUDY_PLAN_NOT_FOUND": "Study plan not found.",
    "STUDY_PLAN_UPDATED": "Study plan updated.",
    "SMS_DELIVERY_STATUS_UPDATED": "SMS delivery status updated.",
    "SMS_DELIVERY_STATUS_NOT_UPDATED": "SMS delivery status not updated.",
    "TAG_EXISTS": "Tag already exists",
    "TAG_NOT_FOUND": "Tag not found",
    "TAG_NOT_EMPTY": "Tags has decks attached to it",
    "INVALID_TAG": "Tag is invalid",
    "CANONICAL_TAG_CONFLICT": "Desired canonical tag is already a synonym.",
    "LIKED_DECKS_NOT_FOUND": "There are no liked decks.",
    "DECK_FOLDER_ADDED": "Dcek folder has been added.",
    "DECK_FOLDER_NOT_FOUND": "Deck folder not found.",
    "NOT_DECK_FOLDER_OWNER": "You need to be owner of this folder to add deck in this folder.",
    "DECK_FOLDER_DELETED": "Deck folder has been deleted",
    "DECK_FOLDER_UPDATED": "Deck folder has been updated",
    "TITLE_NOT_FOUND": "Title not found",
    "CHALLENGE_NOT_FOUND": "Challenge not found",
    "NO_CHALLENGES_FOUND_FOR_REQUESTED_USER": "No Challenge found for requested user",
    "MISSING_CONFIGURATION": "Missing configuration in Challenge",
    "TEST_ID_NOT_FOUND_IN_TEST_SESSIONS_TABLE": "Test id not found in test session table.",
    "TEST_ID_DOES_NOT_BELONG_TO_CURRENT_USER": "Test id does not belong to current user.",
    "PARTICIPANTS_NOT_FOUND": "Challenge Participants not found.",
    "USER_IS_NOT_A_PARTICIPANT": "User has not participated in the Challenge.",
    "CARD_BOOKMARK_CREATED": "Card bookmark created",
    "CARD_BOOKMARK_DELETED": "Card bookmark deleted",
    "BOOKMARK_NOT_FOUND": "Card Bookmark not found",
    "EXAM_CREATED": "Exam created",
    "EXAM_DELETED": "Exam deleted",
    "EXAM_ALREADY_PRESENT": "Exam Already Present",
    "EXAM_NOT_FOUND": "Exam not found",
    "EXAM_TRACK_CREATED": "Exam track created",
    "EXAM_TRACK_DELETED": "Exam track deleted",
    "EXAM_TRACK_ALREADY_PRESENT": "Exam track Already Present",
    "EXAM_TRACK_NOT_FOUND": "Exam track not found",
    "EXAM_TRACK_SUBJECT_CREATED": "Exam track subject created",
    "EXAM_TRACK_SUBJECT_NOT_FOUND": "Exam track subject not found",
    "EXAM_TRACK_SUBJECT_ALREADY_PRESENT": "Exam track subject already present",
    "EXAM_TRACK_SUBJECT_DELETED": "Exam track subject deleted",
    "EXAM_UPDATED": "Exam updated",
    "EXAM_TRACK_UPDATED": "Exam track Updated",
    "EXAM_TRACK_SUBJECT_UPDATED": "Exam track Subject Updated",
    "EXAM_NAME_OR_DESCRIPTION_MISSING": "Exam name or description missing",
    "EXAM_TRACK_UNIT_ALREADY_PRESENT": "Exam Track Unit already present.",
    "EXAM_TRACK_UNIT_ADDED": "Exam Track Unit added.",
    "EXAM_TRACK_UNIT_UPDATED": "Exam Track Unit updated.",
    "EXAM_TRACK_UNIT_NOT_FOUND": "Exam Track Unit not found.",
    "EXAM_TRACK_UNIT_NO_OR_NAME_MISSING": "Exam Track Unit unprocessable entity.",
    "EXAM_TRACK_UNIT_DELETED": "Exam Track Unit deleted.",
    "EXAM_TRACK_TOPIC_ADDED": "Exam Track Topic added.",
    "EXAM_TRACK_TOPIC_ALREADY_PRESENT": "Exam track topic already present",
    "EXAM_TRACK_TOPIC_UPDATED": "Exam Track Topic updated.",
    "EXAM_TRACK_TOPIC_NOT_FOUND": "Exam Track Topic not found.",
    "EXAM_TRACK_TOPIC_NO_OR_NAME_MISSING": "Exam Track Topic unprocessable entity.",
    "EXAM_TRACK_TOPIC_DELETED": "Exam Track Topic deleted.",
    "EXAM_TRACK_ENROLLMENT_UPDATED": "Exam Track Enrollment updated.",
    "EXAM_TRACK_ENROLLMENT_FOUND": "Exam Track Enrollment found.",
    "EXAM_TRACK_ENROLLMENT_NOT_FOUND": "Exam Track Enrollment not found.",
    "EXAM_TRACK_ENROLLMENT_DELETED": "Exam Track Enrollment deleted.",
    "EXAM_TRACK_ENROLLMENT_ADDED": "Exam Track Enrollment added.",
    "NOT_EXAM_TRACK_ENROLLMENT_OWNER": "You need to be owner of this exam track enrollment to delete the enrollment.",
    "DPP_NOT_FOUND": "DPP Not found",
    "DPP_CREATED": "DPP Created",
    "DPP_UPDATED": "DPP Updated",
    "DPP_DELETED": "DPP Deleted",
    "INVALID_PARAMATER": "Invalid parameter",
    "ACTIVITY_NOT_FOUND": "Activity Not Found",
}
