# Generated by Django 4.0.1 on 2022-01-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20220127_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='text',
        ),
    ]
